### ISSUE TITLE
Uncaught (in promise) TypeError: e.map is not a function error on loading default page 

### ISSUE THREAD

**Issue by kr-williams** [KevinJump/uSync8#677]
**Describe the bug**
Im having an issue since i updated to 14.2.2 usync. its now loading the default page in backoffice. When i go to Usync in the backoffice, the three box options for settings, Content , everything dont show up. When i go into settings, all of the settings are "Not set". 

The console thows an error saying " Uncaught (in promise) TypeError: e.map is not a function" inside the default.element.ts file. 
 

**To Reproduce**
1. Go to usync in umbraco backoffice 14
2. Check console 
3. see error 

**Expected behavior**
It should show the three cards for content settings and everything.

**Screenshots**
![umbraco bug](https://github.com/user-attachments/assets/1c67351f-8aed-4afd-b0ba-50207fa97e2d)

**About your Site (please complete the following information):**
 - Umbraco Version:14.3
 - uSync Version:14.2.2
 - Browser [e.g. chrome, safari]: firefox

**Comment by kr-williams** [comment]
issue seem to have resolved itself.

**Comment by KevinJump** [comment]
I think its caching, and replacement of the javascript when upgrades happen. So because the core js file doesn't change between packages and Umbraco's caching is umbraco version based not plugin version based, i think it can remain cached.

a mitigation we wrote in translation manager, and i think we will back port is to append the version to the core js file - but this involves moving to a progromatic production of the manifest (which isn't hard). So we might do that for the next release.

**Comment by MichaelNielsenDK** [comment]
I'm having the same issue
![Screenshot_1](https://github.com/user-attachments/assets/7520abd0-2bc1-4b6c-b43b-3e8ff143c69e)

Unfortunately, I can't seem to get it to resolve itself as OP did. Any suggestions on how to do that? CTRL F5 with network panel open cache disabled marked, isn't helping... 

Umbraco Version: 14.3.1
uSync Version: 14.2.2

**Comment by KevinJump** [comment]
Hi, 

I think 14.2.2. might actually solve this, but just to be 100% sure I've added some extra checks around that bit of code in a new release (v14.2.3). 

https://www.nuget.org/packages/uSync/14.2.3

**Comment by MichaelNielsenDK** [comment]
@KevinJump It is 14.2.2 that is installed, I don’t know why it says 14.2.0 on the Dashboard. 

But @kr-williams also mentions using 14.2.2 and Dashboard there also says 14.2.0 🤷🏼‍♂️

I’ll try 14.2.3 and report back a little later…

**Comment by KevinJump** [comment]
it might be browser caching (although that's what 14.2.2 and 14.2.3 should try to avoid 🤔)

**Comment by MichaelNielsenDK** [comment]
So v14.2.3 did make the error go away... 
https://prnt.sc/1gqM-ZPODwcl 

However the version number is still wrong, and the sections are also still not visible. 

But either going incognito, or clearing local storage and cookies will fix it. 
https://prnt.sc/rlShvHYRTgpF 

CTRL F5 with network panel open and browser cache disabled marked, was not enough to fix it. 

So I don't think it was browser caching alone.

**Comment by stas-lazarev-tga** [comment]
On **v14.2.3**
Encountered the same problem
On Mozilla Firefox the sections are still not visible. Even with the 'Disable Cache' option ticked
![image](https://github.com/user-attachments/assets/21413f07-797e-41ec-9457-67aed86ee934)
it displays v14.2.0 in the left corner there

But logging into Backoffice with Google Chrome resolved the issue. Everything visible again, and v14.2.3 is displayed

**Comment by KevinJump** [comment]
Yeah still figuring out how umbraco, chrome and all the other caching might be working here: 

I think its aggressive caching in the browser somehow (because i don't think Umbraco is serving different javascript files to different browsers). 

We attempt to do something about this because we append the version of uSync to a query string on build, and it does look like that is indeed returned when you upgrade. 

I've being trying to reliably recreate this all night, and i had it happen once, but then it didn't and no amount of resetting and building a new site appears to be making it happen again.

when it did happen i noticed that the API request to get the 'Addons' end point was returning a 302. 
however when i visitied it directly it returned 200, and then suddenly everything was returning 200 🤷 

so maybe going to /umbraco/usync/api/v1/AddOns on your site might unsick it ? (it should return the version you will just see `{"version":"14.2.3"}` in the browser)
